name: code-checks

on:
  pull_request:
    branches: [main]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        version: 0.6.14
    - run: make cicd-check
